### ISSUE TITLE
firstRemoteVideoFrame and videoSizeChanged not triggered on iOS (3.0.1-dev.5)

### ISSUE THREAD

**Issue by rgb1380** [AgoraIO/Flutter-SDK#167] opened 2020-08-05 08:12 UTC
Was forced to use the dev version due to an issue with iPad in the stable release (#140) . 

As the description reads on iOS firstRemoteVideoFrame and videoSizeChanged are not triggered. This was confirmed on two iOS devices (an iPad and an iPhone). firstRemoteAudioDecoded, however, works fine.

Should be easy to replicate on your side. If not, let me know what additional information is required.

**Comment by LichKing-2234** [comment] 2020-08-05 09:07
I will take a look later.

**Comment by LichKing-2234** [comment] 2020-08-06 06:15
fixed in 3.0.1-dev.6

**Comment by rgb1380** [comment] 2020-08-07 03:31
There is a still a residual problem. I can confirm that for remote users the issue has been solved. However, in the stable version, the onVideoSizeChanged is triggered for the local user (uid=0) at the beginning. This gives the initial orientation and size of the video feed for the local user. However, this is not the case for version 3.0.x. 

I can confirm that if you change the orientation of the device onVideoSizeChanged gets triggered correctly. 

The Android version works correctly and as expected.

**Comment by LichKing-2234** [comment] 2020-08-07 06:35
I will check it, thank you.

**Comment by rgb1380** [comment] 2020-08-16 00:09
Any update on this? Can you reopen the issue or should I create a new issue?

**Comment by LichKing-2234** [comment] 2020-08-17 12:34
@rgb1380 

I have tested it. It works fine.

the log from Android.
I/flutter (10019): videoSizeChanged 0 640 360 90

the log from iOS.
flutter: videoSizeChanged 0 640 360 90

**Comment by LichKing-2234** [comment] 2020-08-17 12:35
@rgb1380 maybe you use an iOS simulator? it did not support the camera.

**Comment by rgb1380** [comment] 2020-08-17 12:47
No simulation. The problem was with an iPad.

**Comment by LichKing-2234** [comment] 2020-08-17 12:48
@rgb1380 I will test on iPad

**Comment by rgb1380** [comment] 2020-08-20 02:31
> @rgb1380 I will test on iPad

I have just realised that this is not a problem limited to iPad. This is again due to the fact that onVideoSizeChanged is not triggered properly. I was visually seeing it on iPad because it is usually in landscape mode and my code assumes the device is in portrait mode until it retrieves the rotation angle from onVideoSizeChanged. Here is how I have replicated this on an Android phone:
   1. Connect to a video session.
   2. Note that onVideoSizeChanged gets called as expected.
   3. Leave the session.
   4. Connect to the same session again. 
   5. This time onVideoSizeChanged is not called.

Second time when one connects to the video session there are several lines in the log file like this:
E/RtcEngine(23821): onEvent: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference

**Comment by LichKing-2234** [comment] 2020-08-31 06:10
> > @rgb1380 I will test on iPad
> 
> I have just realised that this is not a problem limited to iPad. This is again due to the fact that onVideoSizeChanged is not triggered properly. I was visually seeing it on iPad because it is usually in landscape mode and my code assumes the device is in portrait mode until it retrieves the rotation angle from onVideoSizeChanged. Here is how I have replicated this on an Android phone:
> 
> 1. Connect to a video session.
> 2. Note that onVideoSizeChanged gets called as expected.
> 3. Leave the session.
> 4. Connect to the same session again.
> 5. This time onVideoSizeChanged is not called.
> 
> Second time when one connects to the video session there are several lines in the log file like this:
> E/RtcEngine(23821): onEvent: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference

this is by design, you can call `destroy`, then the video size cache will be clear.

**Comment by rgb1380** [comment] 2020-08-31 07:30
destroy() is called when we leave the session.

The behaviour in this instance is different from version 1.x. Please double check.

**Comment by LichKing-2234** [comment] 2020-08-31 07:54
I have tried the 1.x version, the `onVideoSizeChanged` not called unless calling the `destroy`.

**Closed** 2020-10-15 03:34 UTC
Labels: bug, question

**Comment by rgb1380** [comment] 2021-01-10 00:13
This is still a bug as of version 3.2.1. As I had said earlier, destroy() is correctly called. Here how to replicate the problem:
1. Connect to a video session.
2. Note that onVideoSizeChanged gets called as expected for the local user.
3. Leave the session (make sure destroy() is called).
4. Connect to the same session again (use the same channel name).
5. This time onVideoSizeChanged is not called for the local user.

**Comment by rgb1380** [comment] 2021-01-16 00:55
@LichKing-2234 can you please reopen this issue? As per my last post this is an unresolved bug.

**Comment by LichKing-2234** [comment] 2021-01-18 03:17
@rgb1380 I will check it today.

**Comment by rgb1380** [comment] 2021-01-28 12:03
Any update please?

**Comment by LichKing-2234** [comment] 2021-02-01 07:30
Sorry for the late reply, I have tested it, it may be a bug from our native SDK, I have given them feedback.
